name: "Community Issue / PR Labeling Workflow""

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  call-central-workflow:
    uses: tenstorrent/tt-github-actions/community/on-community-issue.yml@main

